name: kumbuz
description: "O Kumbuz é uma aplicação inovadora de gestão de finanças pessoais, desenvolvida para ajudar os utilizadores a organizar, monitorizar e otimizar as suas finanças de forma simples e eficiente."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.3.5
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.2
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  firebase_core: ^3.10.0
  onesignal_flutter: ^5.2.9
  currency_formatter: ^2.2.2
  animated_text_kit: ^4.2.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  firebase_auth: ^5.4.0
  firebase_database: ^11.3.0
  firebase_messaging: ^15.2.0
  json_annotation: ^4.9.0
  floor: ^1.5.0
  equatable: ^2.0.7
  date_format: ^2.0.9
  fw_tab_bar: ^0.0.3
  provider: ^6.1.2
  loading_animation_widget: ^1.3.0
  fl_chart: ^0.70.1
  flutter_svg: ^2.0.17
  iconify_flutter: ^0.0.7
  lottie: ^3.3.1
  group_radio_button: ^1.3.0
  firebase_dynamic_links: ^6.1.0
  google_generative_ai: ^0.4.6
  flutter_speed_dial: ^7.0.0
  animated_bottom_navigation_bar: ^1.3.3
  scrollable_positioned_list: ^0.3.8
  table_calendar: ^3.1.3
  mockito: ^5.4.5
  textfield_tags: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  stacked: ^3.4.4
  percent_indicator: ^4.2.4
  multiple_search_selection: ^2.7.1
  dropdown_model_list: ^2.1.5
  function_tree: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/img/
    - assets/animations/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: fonts/poppins/Poppins-Medium.ttf
    - family: Poppins-Thin
      fonts:
        - asset: fonts/poppins/Poppins-Thin.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/poppins/Poppins-SemiBold.ttf
    - family: Poppins-Bold
      fonts:
        - asset: fonts/poppins/Poppins-Bold.ttf